# Generated by Django 4.1.1 on 2022-10-01 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailpelayanan',
            name='iddetailpelayanan',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dokter',
            name='iddokter',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='idpasien',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pelayanan',
            name='idpelayanan',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pendaftaran',
            name='idpendaftaran',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
